import tenisImg from "../assets/slide-image/product.png";

export const cardsInfo = [
  {
    id: 1,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 2,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 3,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 4,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 5,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 6,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 7,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 8,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 9,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 10,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 11,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 12,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 13,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 14,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  },
  {
    id: 15,
    discountPercentual: 30,
    category: "Tênis",
    productName: "K-Swiss V8 - Masculino",
    discountPrice: "$100",
    price: "$200",
    isDiscount: true,
    url: tenisImg,
  }
  
];
